CREATE TYPE "public"."notion_lite_block_type" AS ENUM('text', 'image');--> statement-breakpoint
CREATE TYPE "public"."notion_lite_text_style" AS ENUM('h1', 'h2', 'h3', 'p');--> statement-breakpoint
CREATE TABLE "notion_lite_block" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notion_lite_block_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pageId" integer NOT NULL,
	"type" "notion_lite_block_type" NOT NULL,
	"position" integer NOT NULL,
	"text" text,
	"textStyle" "notion_lite_text_style",
	"imageSrc" text,
	"imageWidth" integer,
	"imageHeight" integer,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "notion_lite_page" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notion_lite_page_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" varchar(128) NOT NULL,
	"title" varchar(256) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "notion_lite_block" ADD CONSTRAINT "notion_lite_block_pageId_notion_lite_page_id_fk" FOREIGN KEY ("pageId") REFERENCES "public"."notion_lite_page"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "blocks_page_id_idx" ON "notion_lite_block" USING btree ("pageId");--> statement-breakpoint
CREATE UNIQUE INDEX "blocks_page_position_idx" ON "notion_lite_block" USING btree ("pageId","position");--> statement-breakpoint
CREATE UNIQUE INDEX "pages_slug_idx" ON "notion_lite_page" USING btree ("slug");